terraform state rm  azurerm_resource_group.rg-mytest
terraform state rm azurerm_network_security_group.rg-mytest__vm-mytest1-nsg
terraform state rm azurerm_managed_disk.rg-mytest__vm-mytest1_OsDisk_1_9030516cccb24ca58da520f0447ae308
terraform state rm azurerm_storage_account.rg-mytest__rgmytestdiag814
terraform state rm azurerm_public_ip.rg-mytest__vm-mytest1-ip
terraform state rm azurerm_network_interface.rg-mytest__vm-mytest1353
terraform state rm azurerm_virtual_machine.rg-mytest__vm-mytest1
terraform state rm  azurerm_resource_group.rg-dwp-sbox-wa-dwk-core
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_virtual_network.rg-dwp-sbox-wa-dwk-core__vnet-dwp-sbox-wa-dwk-core
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_key_vault.rg-dwp-sbox-wa-dwk-core__kv-dwp-sbox-wa-dwk-core
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag01
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag03
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag02
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag04
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkrepo3gvb
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkrepo3gvb-LockDoNotDelete
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__kv-dwp-sbox-wa-dwk-core-LockDoNotDelete
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__vnet-dwp-sbox-wa-dwk-core-LockDoNotDelete
terraform state rm  azurerm_resource_group.rg-dwp-sbox-wa-dwk-core
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_virtual_network.rg-dwp-sbox-wa-dwk-core__vnet-dwp-sbox-wa-dwk-core
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_key_vault.rg-dwp-sbox-wa-dwk-core__kv-dwp-sbox-wa-dwk-core
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag01
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag03
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag02
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag04
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkrepo3gvb
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkrepo3gvb-LockDoNotDelete
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__kv-dwp-sbox-wa-dwk-core-LockDoNotDelete
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__vnet-dwp-sbox-wa-dwk-core-LockDoNotDelete
terraform state rm  azurerm_resource_group.rg-dwp-sbox-wa-dwk-core
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_route_table.rg-dwp-sbox-wa-dwk-core__udr-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_network_security_group.rg-dwp-sbox-wa-dwk-core__nsg-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_virtual_network.rg-dwp-sbox-wa-dwk-core__vnet-dwp-sbox-wa-dwk-core
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-fe01
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-fe02
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-be01
terraform state rm azurerm_subnet.rg-dwp-sbox-wa-dwk-core__sub-dwp-sbox-wa-dwk-be02
terraform state rm azurerm_key_vault.rg-dwp-sbox-wa-dwk-core__kv-dwp-sbox-wa-dwk-core
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag01
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag03
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag02
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkdiag04
terraform state rm azurerm_storage_account.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkrepo3gvb
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__strdwpsboxwadwkrepo3gvb-LockDoNotDelete
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__kv-dwp-sbox-wa-dwk-core-LockDoNotDelete
terraform state rm azurerm_management_lock.rg-dwp-sbox-wa-dwk-core__vnet-dwp-sbox-wa-dwk-core-LockDoNotDelete
terraform state rm  azurerm_resource_group.rg-mytest
terraform state rm azurerm_network_security_group.rg-mytest__vm-mytest1-nsg
terraform state rm azurerm_managed_disk.rg-mytest__vm-mytest1_OsDisk_1_9030516cccb24ca58da520f0447ae308
terraform state rm azurerm_storage_account.rg-mytest__rgmytestdiag814
terraform state rm azurerm_public_ip.rg-mytest__vm-mytest1-ip
terraform state rm azurerm_network_interface.rg-mytest__vm-mytest1353
terraform state rm azurerm_virtual_machine.rg-mytest__vm-mytest1
